add_newline = false
format = """$character"""
right_format = """$all"""
continuation_prompt = '... '

[character]
success_symbol = "[ ->](bold green)"
error_symbol = "[ ->](bold red)"

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"

[git_status]
style = "bold yellow"

[git_state]
style = "bold yellow"

[git_branch]
style = "bold blue"
format = '[$symbol$branch(:$remote_branch)]($style) '

[package]
disabled = true

[hostname]
ssh_symbol = 'ğŸ›°ï¸ '

[nix_shell]
format = '[$symbol $state]($style)'
symbol = 'â„ï¸'
impure_msg = '+ '
pure_msg = ''
style = 'blue'

[nodejs]
format = '[$symbol($version )]($style)'

[java]
format = '[${symbol}(${version} )]($style)'

[dotnet]
format = '[$symbol($version )(ğŸ¯ $tfm )]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[golang]
format = '[$symbol($version )]($style)'

[rust]
format = '[$symbol($version )]($style)'
